on:
  schedule:
  - cron: "30 17 * * 5" # Friday afternoon
  workflow_dispatch:
  pull_request:
    paths:
    - .github/renovate.json
    - .github/workflows/renovate.yml

jobs:
  upgrade-dependencies:
    uses: bmillwood/renovateconfig/.github/workflows/renovate.yml@8a4cddef5696cc92b5c881fb207f1dbb3df90db9 # main
    secrets: inherit
